import { createClient } from "jsr:@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const SYMBOL="XAUUSD_PROXY_GC",MODEL="logistic_direction_15m_proxy",FV="bootstrap_v1",FNS=["rsi_centered","wt_gap","squeeze_scaled","return_1","atr_pct"],COST=.00015;
const sig=(x:number)=>1/(1+Math.exp(-Math.max(-30,Math.min(30,x))));const mean=(a:number[])=>a.reduce((s,x)=>s+x,0)/Math.max(a.length,1);const std=(a:number[],m:number)=>Math.sqrt(mean(a.map(x=>(x-m)*(x-m))))||1;
async function setting(k:string,f:string){const{data}=await db.from("runtime_settings").select("value").eq("key",k).limit(1).maybeSingle();return data?.value??f}
async function load(){const all:any[]=[];for(let page=0;page<8;page++){const from=page*1000,{data,error}=await db.from("gold_market_features").select("ts,close,rsi,atr,wt1,wt2,squeeze").eq("symbol",SYMBOL).eq("feature_set_version",FV).order("ts",{ascending:true}).range(from,from+999);if(error)throw error;if(!data?.length)break;all.push(...data);if(data.length<1000)break}return all.slice(-7000)}
type Fit={mu:number[];sd:number[];w:number[];b:number};
function fit(X:number[][],Y:number[],n:number):Fit{const mu=FNS.map((_,j)=>mean(X.slice(0,n).map(x=>x[j]))),sd=FNS.map((_,j)=>std(X.slice(0,n).map(x=>x[j]),mu[j])),Z=X.slice(0,n).map(x=>x.map((v,j)=>(v-mu[j])/sd[j]));let w=new Array(FNS.length).fill(0),b=0;for(let e=0;e<450;e++){const gw=new Array(w.length).fill(0);let gb=0;for(let i=0;i<n;i++){let z=b;for(let j=0;j<w.length;j++)z+=w[j]*Z[i][j];const d=sig(z)-Y[i];gb+=d;for(let j=0;j<w.length;j++)gw[j]+=d*Z[i][j]}b-=.05*gb/n;for(let j=0;j<w.length;j++)w[j]-=.05*(gw[j]/n+.001*w[j])}return{mu,sd,w,b}}
function prob(x:number[],f:Fit){let z=f.b;for(let j=0;j<f.w.length;j++)z+=f.w[j]*((x[j]-f.mu[j])/f.sd[j]);return sig(z)}
function evalFold(X:number[][],Y:number[],R:number[],s:number,e:number,f:Fit){const ps:number[]=[],net:number[]=[];let wins=0,correct=0;for(let i=s;i<e;i++){const p=prob(X[i],f);ps.push(p);if((p>=.5?1:0)===Y[i])correct++;const side=p>=.62?1:p<=.38?-1:0;if(side){const rr=side*R[i]-COST;net.push(rr);if(rr>0)wins++}}const brier=mean(ps.map((p,i)=>(p-Y[s+i])**2)),eps=1e-9,logloss=-mean(ps.map((p,i)=>Y[s+i]*Math.log(p+eps)+(1-Y[s+i])*Math.log(1-p+eps)));let eq=0,peak=0,mdd=0;for(const x of net){eq+=x;peak=Math.max(peak,eq);mdd=Math.min(mdd,eq-peak)}return{test_rows:e-s,brier,logloss,accuracy:correct/Math.max(e-s,1),trades:net.length,coverage:net.length/Math.max(e-s,1),win_rate:net.length?wins/net.length:0,mean_net_return:net.length?mean(net):0,total_net_return:net.reduce((a,b)=>a+b,0),max_drawdown_return:mdd}}

Deno.serve(async(req:Request)=>{
  if(req.method!=="POST"&&req.method!=="GET")return new Response("method not allowed",{status:405});const token=req.headers.get("x-refresh-token"),expected=await setting("public_refresh_token","");if(!expected||token!==expected)return Response.json({ok:false,error:"unauthorized"},{status:401});
  const{data:loop}=await db.from("closed_loop_runs").insert({run_type:"retrain",status:"running",symbol:SYMBOL}).select("id").single();
  let request:any=null;const{data:pending}=await db.from("retraining_requests").select("*").eq("symbol",SYMBOL).eq("model_name",MODEL).eq("status","pending").order("requested_at",{ascending:true}).limit(1).maybeSingle();request=pending;
  if(!request){const day=new Date().toISOString().slice(0,10),key=`schedule:${MODEL}:${day}`,{data:created,error}=await db.from("retraining_requests").insert({idempotency_key:key,trigger_type:"schedule",symbol:SYMBOL,model_name:MODEL,status:"pending",reason:{source:"daily_cron"}}).select("*").single();if(error&&String(error.code)==="23505"){if(loop?.id)await db.from("closed_loop_runs").update({status:"skipped",finished_at:new Date().toISOString(),metadata:{reason:"daily_training_already_recorded"}}).eq("id",loop.id);return Response.json({ok:true,skipped:"daily_training_already_recorded"})}if(error)throw error;request=created}
  await db.from("retraining_requests").update({status:"running",started_at:new Date().toISOString()}).eq("id",request.id);
  try{
    const rows=await load();if(rows.length<1200)throw new Error(`need >=1200 feature rows, have ${rows.length}`);const X:number[][]=[],Y:number[]=[],R:number[]=[],T:string[]=[];for(let i=1;i<rows.length-15;i++){const r=rows[i],p=rows[i-1],f=rows[i+15];if([r.close,r.rsi,r.atr,r.wt1,r.wt2,r.squeeze,p.close,f.close].some(v=>v==null||!Number.isFinite(Number(v))))continue;const ret=Math.log(Number(f.close)/Number(r.close));X.push([(Number(r.rsi)-50)/50,Number(r.wt1)-Number(r.wt2),Number(r.squeeze)/40,Math.log(Number(r.close)/Number(p.close)),Number(r.atr)/Math.max(Number(r.close),1)]);Y.push(ret>.00010?1:0);R.push(ret);T.push(r.ts)}const n=X.length;if(n<1000)throw new Error(`insufficient usable rows ${n}`);
    const b=[Math.floor(n*.55),Math.floor(n*.70),Math.floor(n*.85),n],folds:any[]=[];for(let k=0;k<3;k++){const s=b[k],e=b[k+1];if(s<500||e-s<150)continue;folds.push({fold:k+1,train_rows:s,test_start:T[s],test_end:T[e-1],...evalFold(X,Y,R,s,e,fit(X,Y,s))})}if(folds.length<3)throw new Error(`need 3 walk-forward folds, have ${folds.length}`);
    const tr=folds.reduce((s,x)=>s+x.test_rows,0),nt=folds.reduce((s,x)=>s+x.trades,0),weighted=(name:string)=>folds.reduce((s,x)=>s+Number(x[name])*x.test_rows,0)/tr,total=folds.reduce((s,x)=>s+x.total_net_return,0),metrics:any={protocol:"expanding_walk_forward_3fold",folds,test_rows:tr,brier:weighted("brier"),logloss:weighted("logloss"),accuracy:weighted("accuracy"),trades:nt,coverage:nt/tr,win_rate:nt?folds.reduce((s,x)=>s+x.win_rate*x.trades,0)/nt:0,mean_net_return:nt?total/nt:0,total_net_return:total,max_drawdown_return:Math.min(...folds.map(x=>x.max_drawdown_return)),positive_folds:folds.filter(x=>x.mean_net_return>0).length,threshold_long:.62,threshold_short:.38,backtest_cost_per_trade:COST,proxy_only:true};
    const eligible=metrics.test_rows>=600&&metrics.trades>=30&&metrics.positive_folds>=2&&metrics.mean_net_return>0&&metrics.brier<.26&&metrics.max_drawdown_return>-.05,final=fit(X,Y,n),version=`logistic_proxy_wf_${new Date().toISOString().replace(/[-:.TZ]/g,"")}`,dataset=`yahoo_gc_futures_1m_${rows[0].ts}_${rows.at(-1).ts}`,params={feature_names:FNS,mean:final.mu,std:final.sd,weights:final.w,intercept:final.b,horizon_minutes:15,long_threshold:.62,short_threshold:.38,training:"expanding_walk_forward_evaluation_then_refit_all",proxy_only:true},{data:prev}=await db.from("model_runs").select("id,model_version,metrics").eq("model_name",MODEL).eq("status","champion").order("created_at",{ascending:false}).limit(1).maybeSingle();let promote=eligible;if(prev?.metrics){const pm:any=prev.metrics;promote=eligible&&metrics.brier<=Number(pm.brier??1)+.01&&metrics.mean_net_return>=Number(pm.mean_net_return??-1)*.90}
    const{data:mr,error:me}=await db.from("model_runs").insert({model_name:MODEL,model_version:version,dataset_version:dataset,feature_set_version:FV,train_start:T[0],train_end:T.at(-1),metrics,params,status:"candidate"}).select("id").single();if(me)throw me;await db.from("backtest_runs").insert({model_version:version,dataset_version:dataset,start_ts:folds[0].test_start,end_ts:folds.at(-1).test_end,assumptions:{instrument:"GC=F proxy",horizon_minutes:15,cost_per_trade_return:COST,walk_forward:true,folds:3,live_promotion_allowed:false},metrics});
    if(promote){if(prev?.id)await db.from("model_runs").update({status:"retired"}).eq("id",prev.id);await db.from("model_runs").update({status:"champion"}).eq("id",mr.id);await db.from("model_promotion_events").insert({model_version:version,from_stage:"backtest",to_stage:"paper",decision:"promote",gate_metrics:metrics,reason:"Passed three-fold walk-forward proxy gate; live promotion remains forbidden.",actor:"train-baseline"})}else await db.from("model_promotion_events").insert({model_version:version,from_stage:"backtest",to_stage:"candidate",decision:"hold",gate_metrics:metrics,reason:"Did not pass the walk-forward paper-only gate or champion comparison.",actor:"train-baseline"});
    await db.from("retraining_requests").update({status:"succeeded",finished_at:new Date().toISOString(),model_version_before:request.model_version_before??prev?.model_version??null,model_version_after:promote?version:prev?.model_version??null,reason:{...(request.reason??{}),metrics,promoted:promote}}).eq("id",request.id);if(loop?.id)await db.from("closed_loop_runs").update({status:"success",finished_at:new Date().toISOString(),model_version:version,counts:{rows:n,folds:3,trades:metrics.trades},metrics,metadata:{promoted_to_paper:promote,previous_champion:prev?.model_version??null,live_enabled:false}}).eq("id",loop.id);return Response.json({ok:true,modelVersion:version,promotedToPaper:promote,metrics,liveEnabled:false})
  }catch(e){await db.from("retraining_requests").update({status:"failed",finished_at:new Date().toISOString(),error:String(e)}).eq("id",request.id);if(loop?.id)await db.from("closed_loop_runs").update({status:"failed",finished_at:new Date().toISOString(),error:String(e)}).eq("id",loop.id);return Response.json({ok:false,error:String(e)},{status:500})}
});
