import { createClient } from "jsr:@supabase/supabase-js@2";
const url=Deno.env.get("SUPABASE_URL")!,key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,db=createClient(url,key,{auth:{persistSession:false}});
const SYMBOL="XAUUSD_PROXY_GC",MODEL="logistic_direction_15m_proxy",FV="bootstrap_v1",FNS=["rsi_centered","wt_gap","squeeze_scaled","return_1","atr_pct"];
const sig=(x:number)=>1/(1+Math.exp(-Math.max(-30,Math.min(30,x))));
const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const std=(a:number[],m:number)=>Math.sqrt(mean(a.map(x=>(x-m)*(x-m))))||1;
async function authorized(req:Request){const supplied=req.headers.get("x-refresh-token");const{data}=await db.from("runtime_settings").select("value").eq("key","public_refresh_token").limit(1).maybeSingle();return Boolean(data?.value&&supplied===data.value);}
async function load(){const all:any[]=[];for(let page=0;page<7;page++){const from=page*1000,to=from+999,{data,error}=await db.from("gold_market_features").select("ts,close,rsi,atr,wt1,wt2,squeeze").eq("symbol",SYMBOL).eq("feature_set_version",FV).order("ts",{ascending:true}).range(from,to);if(error)throw error;if(!data?.length)break;all.push(...data);if(data.length<1000)break;}return all.slice(-6000);}
function fit(X:number[][],Y:number[],end:number,epochs=350){const mu=FNS.map((_,j)=>mean(X.slice(0,end).map(x=>x[j]))),sd=FNS.map((_,j)=>std(X.slice(0,end).map(x=>x[j]),mu[j]));let w=new Array(FNS.length).fill(0),b=0;const lr=.05,l2=.001;for(let e=0;e<epochs;e++){const gw=new Array(w.length).fill(0);let gb=0;for(let i=0;i<end;i++){let z=b;for(let j=0;j<w.length;j++)z+=w[j]*((X[i][j]-mu[j])/sd[j]);const d=sig(z)-Y[i];gb+=d;for(let j=0;j<w.length;j++)gw[j]+=d*((X[i][j]-mu[j])/sd[j]);}b-=lr*gb/end;for(let j=0;j<w.length;j++)w[j]-=lr*(gw[j]/end+l2*w[j]);}return{mu,sd,w,b};}
function predict(model:any,x:number[]){let z=model.b;for(let j=0;j<model.w.length;j++)z+=model.w[j]*((x[j]-model.mu[j])/model.sd[j]);return sig(z);}
function metrics(probs:number[],ys:number[],rets:number[]){const eps=1e-9,brier=mean(probs.map((p,i)=>(p-ys[i])**2)),logloss=-mean(probs.map((p,i)=>ys[i]*Math.log(p+eps)+(1-ys[i])*Math.log(1-p+eps))),accuracy=mean(probs.map((p,i)=>(p>=.5?1:0)===ys[i]?1:0));const net:number[]=[];let wins=0;for(let i=0;i<probs.length;i++){const side=probs[i]>=.62?1:probs[i]<=.38?-1:0;if(side){const rr=side*rets[i]-.00015;net.push(rr);if(rr>0)wins++;}}let eq=0,peak=0,mdd=0;for(const x of net){eq+=x;peak=Math.max(peak,eq);mdd=Math.min(mdd,eq-peak);}return{test_rows:probs.length,brier,logloss,accuracy,trades:net.length,coverage:probs.length?net.length/probs.length:0,win_rate:net.length?wins/net.length:0,mean_net_return:net.length?mean(net):0,total_net_return:net.reduce((s,x)=>s+x,0),max_drawdown_return:mdd};}

Deno.serve(async(req:Request)=>{
  if(req.method!=="POST"&&req.method!=="GET")return new Response("method not allowed",{status:405});
  if(!(await authorized(req)))return Response.json({ok:false,error:"unauthorized"},{status:401});
  const{data:run}=await db.from("closed_loop_runs").insert({run_type:"retrain",status:"running",symbol:SYMBOL}).select("id").single();
  const finish=async(status:string,patch:any={})=>{if(run?.id)await db.from("closed_loop_runs").update({status,finished_at:new Date().toISOString(),...patch}).eq("id",run.id);};
  try{
    const rows=await load();if(rows.length<1200){await finish("skipped",{metadata:{reason:"insufficient features",rows:rows.length}});return Response.json({ok:false,error:`need >=1200 feature rows, have ${rows.length}`},{status:409});}
    const X:number[][]=[],Y:number[]=[],R:number[]=[],T:string[]=[];
    for(let i=1;i<rows.length-15;i++){const r=rows[i],p=rows[i-1],f=rows[i+15];if([r.close,r.rsi,r.atr,r.wt1,r.wt2,r.squeeze,p.close,f.close].some(v=>v==null||!Number.isFinite(Number(v))))continue;const ret=Math.log(Number(f.close)/Number(r.close));X.push([(Number(r.rsi)-50)/50,Number(r.wt1)-Number(r.wt2),Number(r.squeeze)/40,Math.log(Number(r.close)/Number(p.close)),Number(r.atr)/Math.max(Number(r.close),1)]);Y.push(ret>0.00010?1:0);R.push(ret);T.push(r.ts);}
    const n=X.length;if(n<1000)throw new Error(`insufficient usable rows ${n}`);
    const foldDefs=[[.50,.65],[.65,.78],[.78,1.00]],foldMetrics:any[]=[],allP:number[]=[],allY:number[]=[],allR:number[]=[];
    for(let f=0;f<foldDefs.length;f++){const trainEnd=Math.floor(n*foldDefs[f][0]),testEnd=Math.floor(n*foldDefs[f][1]);if(trainEnd<500||testEnd-trainEnd<100)continue;const model=fit(X,Y,trainEnd,300),p:number[]=[],y:number[]=[],r:number[]=[];for(let i=trainEnd;i<testEnd;i++){p.push(predict(model,X[i]));y.push(Y[i]);r.push(R[i]);}const m=metrics(p,y,r);foldMetrics.push({fold:f+1,train_rows:trainEnd,test_start:T[trainEnd],test_end:T[testEnd-1],...m});allP.push(...p);allY.push(...y);allR.push(...r);}
    if(foldMetrics.length<3)throw new Error("walk-forward folds unavailable");
    const agg:any=metrics(allP,allY,allR),positiveFolds=foldMetrics.filter(x=>x.mean_net_return>0).length;
    Object.assign(agg,{walk_forward:true,folds:foldMetrics,positive_folds:positiveFolds,threshold_long:.62,threshold_short:.38,label_cost_buffer:.00010,backtest_cost_per_trade:.00015,proxy_only:true,probability_semantics:"P(up_15m)"});

    const finalModel=fit(X,Y,n,450),params={feature_names:FNS,mean:finalModel.mu,std:finalModel.sd,weights:finalModel.w,intercept:finalModel.b,horizon_minutes:15,long_threshold:.62,short_threshold:.38,training:"3-fold expanding chronological walk-forward + final refit on all available data",probability_semantics:"P(up_15m)",proxy_only:true,data_start:T[0],data_end:T[n-1]};
    const eligible=agg.test_rows>=500&&agg.trades>=30&&agg.mean_net_return>0&&agg.brier<.26&&agg.max_drawdown_return>-.05&&positiveFolds>=2;
    const{data:prev}=await db.from("model_runs").select("id,model_version,metrics,params").eq("model_name",MODEL).eq("status","champion").order("created_at",{ascending:false}).limit(1).maybeSingle();
    if((prev?.params as any)?.data_end===params.data_end){await finish("skipped",{model_version:prev.model_version,metadata:{reason:"no new training data",data_end:params.data_end}});return Response.json({ok:true,skipped:"no_new_data",modelVersion:prev.model_version,promotedToPaper:false,metrics:prev.metrics});}
    let promote=eligible;if(prev?.metrics){const pm:any=prev.metrics;promote=eligible&&agg.brier<=Number(pm.brier??1)+.01&&agg.mean_net_return>=Number(pm.mean_net_return??-1)*.90;}
    const version=`logistic_proxy_wf_${new Date().toISOString().replace(/[-:.TZ]/g,"")}`,dataset=`yahoo_gc_futures_1m_${T[0]}_${T[n-1]}`;
    const{data:mr,error:me}=await db.from("model_runs").insert({model_name:MODEL,model_version:version,dataset_version:dataset,feature_set_version:FV,train_start:T[0],train_end:T[n-1],metrics:agg,params,status:"candidate"}).select("id").single();if(me)throw me;
    await db.from("backtest_runs").insert({model_version:version,dataset_version:dataset,start_ts:foldMetrics[0].test_start,end_ts:foldMetrics.at(-1).test_end,assumptions:{instrument:"GC=F proxy",horizon_minutes:15,cost_per_trade_return:.00015,walk_forward:true,folds:foldMetrics.length,live_promotion_allowed:false},metrics:agg});
    if(promote){if(prev?.id)await db.from("model_runs").update({status:"retired"}).eq("id",prev.id);await db.from("model_runs").update({status:"champion"}).eq("id",mr.id);await db.from("model_promotion_events").insert({model_version:version,from_stage:"backtest",to_stage:"paper",decision:"promote",gate_metrics:agg,reason:"Passed leakage-safe proxy walk-forward paper gate; broker/live promotion remains forbidden.",actor:"train-baseline-v2"});}else await db.from("model_promotion_events").insert({model_version:version,from_stage:"backtest",to_stage:"candidate",decision:"hold",gate_metrics:agg,reason:"Did not pass the paper-only walk-forward gate or did not improve sufficiently over champion.",actor:"train-baseline-v2"});
    await finish("success",{model_version:version,output_watermark:T[n-1],counts:{usable_rows:n,oos_rows:agg.test_rows,oos_trades:agg.trades,folds:foldMetrics.length},metrics:{promoted_to_paper:promote,brier:agg.brier,mean_net_return:agg.mean_net_return,max_drawdown_return:agg.max_drawdown_return,positive_folds:positiveFolds}});
    return Response.json({ok:true,modelVersion:version,promotedToPaper:promote,metrics:agg,params:{feature_names:FNS,weights:finalModel.w,intercept:finalModel.b}});
  }catch(e){const error=String(e);await finish("failed",{error});return Response.json({ok:false,error},{status:500});}
});
